//! Detection + audit event bus.
//!
//! The public package emits structured events; sinks consume them.
//! Enterprise additions: SIEM forwarder, central escrow alert, webhook.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub enum Severity {
    Info,
    Warning,
    Critical,
}

/// Where a `HoneyTriggered` came from.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum TripwireSource {
    /// Random honey name generated by `Mapper`; catches blind guessing.
    Honey,
    /// Scrambled name from a previous epoch; catches an attacker using
    /// cached intel from before the last rotation.
    Stale,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "event", rename_all = "snake_case")]
pub enum Event {
    HoneyTriggered {
        epoch: u64,
        names: Vec<String>,
        /// Source tag from the wrapper.
        source: TripwireSource,
        /// PID of the wrapper script (it exits 127 immediately; do NOT
        /// act on this PID — use `triggering_pid` instead).
        wrapper_pid: u32,
        /// PID of the process that exec'd the wrapper.  This is the
        /// process a response policy may want to act on.  None if the
        /// wrapper could not read /proc.
        triggering_pid: Option<u32>,
        /// Start-time (in clock ticks since boot) of `triggering_pid`,
        /// captured at trigger time.  A responder MUST compare this
        /// against the current `/proc/<pid>/stat` start-time before
        /// acting on the PID — otherwise PID reuse can make the
        /// responder hit an innocent process.
        triggering_pid_start: Option<u64>,
        /// Free-form hint for human-readable sinks (also used by
        /// pre-structured-field code paths).
        process_hint: String,
    },
    UnlockFailed {
        epoch: u64,
        backend: String,
    },
    RotationComplete {
        old_epoch: u64,
        new_epoch: u64,
    },
    VaultSealed {
        epoch: u64,
        backend: String,
    },
}

impl Event {
    pub fn severity(&self) -> Severity {
        match self {
            Event::HoneyTriggered { .. } => Severity::Critical,
            Event::UnlockFailed { .. } => Severity::Warning,
            _ => Severity::Info,
        }
    }
}

pub trait EventSink: Send + Sync {
    fn emit(&self, event: &Event);
}

pub struct StderrSink;

impl EventSink for StderrSink {
    fn emit(&self, event: &Event) {
        eprintln!(
            "[babbleon] {}",
            serde_json::to_string(event).unwrap_or_default()
        );
    }
}

/// Append-only JSONL sink for local audit logs.  Each emit takes the
/// write lock briefly; suitable for low-frequency security events.
pub struct JsonlFileSink {
    path: std::path::PathBuf,
    lock: std::sync::Mutex<()>,
}

impl JsonlFileSink {
    pub fn new(path: impl Into<std::path::PathBuf>) -> Self {
        Self {
            path: path.into(),
            lock: std::sync::Mutex::new(()),
        }
    }
}

impl EventSink for JsonlFileSink {
    fn emit(&self, event: &Event) {
        use std::io::Write;
        let _g = self.lock.lock().unwrap_or_else(|e| e.into_inner());
        let line = match serde_json::to_string(event) {
            Ok(s) => s,
            Err(_) => return,
        };
        if let Ok(mut f) = std::fs::OpenOptions::new()
            .create(true)
            .append(true)
            .open(&self.path)
        {
            let _ = writeln!(f, "{line}");
        }
    }
}

/// Reads honey-tripwire access events from the named FIFO and forwards them
/// to an `EventBus`.
///
/// The honey wrapper scripts write a minimal JSON line to `HONEY_FIFO`.
/// This reader opens the FIFO (blocking until a writer appears), parses each
/// line, and emits `Event::HoneyTriggered` to the bus.
///
/// Call `spawn(bus, epoch, fifo_path)` from the trusted-tier daemon.  The
/// returned `JoinHandle` runs until the FIFO is removed or an error occurs.
pub struct HoneyFifoReader;

#[derive(serde::Deserialize)]
struct HoneyLine {
    ts: Option<u64>,
    pid: Option<u64>,
    ppid: Option<u64>,
    ppid_start: Option<u64>,
    source: Option<String>,
    honey: String,
    args: Option<String>,
}

impl HoneyFifoReader {
    /// Spawn a background thread that reads from `fifo_path` and emits events.
    ///
    /// The thread exits cleanly when the FIFO is deleted or read returns EOF.
    pub fn spawn(
        bus: std::sync::Arc<EventBus>,
        epoch: u64,
        fifo_path: impl AsRef<std::path::Path> + Send + 'static,
    ) -> std::thread::JoinHandle<()> {
        std::thread::spawn(move || {
            Self::run(bus, epoch, fifo_path.as_ref());
        })
    }

    fn run(bus: std::sync::Arc<EventBus>, epoch: u64, fifo_path: &std::path::Path) {
        use std::io::{BufRead, BufReader};

        // Create the FIFO if it doesn't exist.
        #[cfg(unix)]
        {
            if !fifo_path.exists() {
                let path_cstr = std::ffi::CString::new(fifo_path.to_string_lossy().as_bytes())
                    .unwrap_or_default();
                // SAFETY: `mkfifo(2)` reads a NUL-terminated C string we own
                // (allocated by `CString::new` above; lives for the duration
                // of this call) and takes a plain `mode_t`.  Both arguments
                // are valid scalars; no aliasing or lifetime concern.  The
                // return value is ignored — if the FIFO already exists
                // (EEXIST) or fails for any other reason, the subsequent
                // `OpenOptions::new().open()` will surface the error.
                unsafe {
                    libc::mkfifo(path_cstr.as_ptr(), 0o600);
                }
            }
        }

        let f = match std::fs::OpenOptions::new().read(true).open(fifo_path) {
            Ok(f) => f,
            Err(e) => {
                tracing::warn!("honey fifo open failed: {e}");
                return;
            }
        };

        let reader = BufReader::new(f);
        for line in reader.lines() {
            let line = match line {
                Ok(l) if !l.is_empty() => l,
                _ => break,
            };
            if let Ok(entry) = serde_json::from_str::<HoneyLine>(&line) {
                let source = match entry.source.as_deref() {
                    Some("stale") => TripwireSource::Stale,
                    _ => TripwireSource::Honey,
                };
                let triggering_pid = entry.ppid.filter(|&p| p != 0).map(|p| p as u32);
                let triggering_pid_start = entry.ppid_start.filter(|&s| s != 0);
                let hint = format!(
                    "pid={} ppid={} ts={} source={:?} args={}",
                    entry.pid.unwrap_or(0),
                    entry.ppid.unwrap_or(0),
                    entry.ts.unwrap_or(0),
                    source,
                    entry.args.as_deref().unwrap_or("")
                );
                bus.emit(Event::HoneyTriggered {
                    epoch,
                    names: vec![entry.honey],
                    source,
                    wrapper_pid: entry.pid.unwrap_or(0) as u32,
                    triggering_pid,
                    triggering_pid_start,
                    process_hint: hint,
                });
            }
        }
    }
}

pub struct EventBus {
    sinks: Vec<Box<dyn EventSink>>,
}

impl Default for EventBus {
    fn default() -> Self {
        Self {
            sinks: vec![Box::new(StderrSink)],
        }
    }
}

impl EventBus {
    pub fn new() -> Self {
        Self { sinks: Vec::new() }
    }

    pub fn add_sink(&mut self, sink: Box<dyn EventSink>) {
        self.sinks.push(sink);
    }

    pub fn emit(&self, event: Event) {
        for sink in &self.sinks {
            // A panicking sink must not break others.
            let result =
                std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| sink.emit(&event)));
            let _ = result;
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::{Arc, Mutex};

    struct Capture(Arc<Mutex<Vec<Event>>>);
    impl EventSink for Capture {
        fn emit(&self, e: &Event) {
            self.0.lock().unwrap().push(e.clone());
        }
    }

    #[test]
    fn jsonl_sink_writes_lines() {
        let tmp = tempfile::tempdir().unwrap();
        let path = tmp.path().join("audit.jsonl");
        let sink = JsonlFileSink::new(&path);
        sink.emit(&Event::RotationComplete {
            old_epoch: 1,
            new_epoch: 2,
        });
        sink.emit(&Event::VaultSealed {
            epoch: 2,
            backend: "soft".into(),
        });
        let content = std::fs::read_to_string(&path).unwrap();
        let lines: Vec<&str> = content.lines().collect();
        assert_eq!(lines.len(), 2);
        let first: Event = serde_json::from_str(lines[0]).unwrap();
        assert!(matches!(
            first,
            Event::RotationComplete {
                old_epoch: 1,
                new_epoch: 2
            }
        ));
    }

    #[cfg(unix)]
    #[test]
    fn honey_fifo_reader_fires_event() {
        use std::io::Write;
        use std::sync::Arc;

        let tmp = tempfile::tempdir().unwrap();
        let fifo_path = tmp.path().join("honey.fifo");

        // Create FIFO.
        // SAFETY: same justification as the production path in
        // `HoneyFifoReader::run` — `mkfifo(2)` takes a NUL-terminated C
        // string we own and a scalar mode.  Return code is ignored
        // because the test will fail explicitly if the FIFO is unusable.
        let cstr =
            std::ffi::CString::new(fifo_path.to_string_lossy().as_bytes()).unwrap();
        unsafe {
            libc::mkfifo(cstr.as_ptr(), 0o600);
        }

        let store = Arc::new(Mutex::new(vec![]));
        let mut bus = EventBus::new();
        bus.add_sink(Box::new(Capture(store.clone())));
        let bus = Arc::new(bus);

        let fp = fifo_path.clone();
        let handle = HoneyFifoReader::spawn(bus.clone(), 7, fp);

        // Give the reader thread time to open the FIFO.
        std::thread::sleep(std::time::Duration::from_millis(50));

        // Write a honey line as if a honey wrapper did it.
        {
            let mut f = std::fs::OpenOptions::new()
                .write(true)
                .open(&fifo_path)
                .unwrap();
            writeln!(
                f,
                r#"{{"ts":1234,"pid":9999,"ppid":1234,"ppid_start":555,"source":"stale","honey":"xq-marble-fern","args":"--list"}}"#
            )
            .unwrap();
        }
        // Close the FIFO so the reader sees EOF.
        std::fs::remove_file(&fifo_path).ok();

        handle.join().ok();

        let s = store.lock().unwrap();
        assert_eq!(s.len(), 1, "expected exactly one HoneyTriggered event");
        match &s[0] {
            Event::HoneyTriggered {
                epoch,
                names,
                source,
                wrapper_pid,
                triggering_pid,
                triggering_pid_start,
                process_hint,
            } => {
                assert_eq!(*epoch, 7);
                assert_eq!(names[0], "xq-marble-fern");
                assert_eq!(*source, TripwireSource::Stale);
                assert_eq!(*wrapper_pid, 9999);
                assert_eq!(*triggering_pid, Some(1234));
                assert_eq!(*triggering_pid_start, Some(555));
                assert!(process_hint.contains("9999"), "wrapper pid should appear in hint");
            }
            other => panic!("unexpected event: {other:?}"),
        }
    }

    #[test]
    fn fanout_and_severity() {
        let store = Arc::new(Mutex::new(vec![]));
        let mut bus = EventBus::new();
        bus.add_sink(Box::new(Capture(store.clone())));
        bus.emit(Event::HoneyTriggered {
            epoch: 1,
            names: vec!["x".into()],
            source: TripwireSource::Honey,
            wrapper_pid: 42,
            triggering_pid: None,
            triggering_pid_start: None,
            process_hint: "pid=42".into(),
        });
        bus.emit(Event::RotationComplete {
            old_epoch: 0,
            new_epoch: 1,
        });
        let s = store.lock().unwrap();
        assert_eq!(s.len(), 2);
        assert!(matches!(s[0].severity(), Severity::Critical));
        assert!(matches!(s[1].severity(), Severity::Info));
    }
}
