//! The per-host secret — the only secret on a Babbleon-protected host.
//!
//! # What this defeats
//!
//! Babbleon's security argument is Kerckhoffs: the algorithm and
//! wordlist are public; the **per-host random secret is the only
//! secret**.  Every per-epoch mapping, every honey-name list, every
//! tripwire identifier, every wrapper-padding fingerprint is
//! derived from this secret via HKDF.  Reading this secret from
//! memory or disk is the single attacker objective with maximum
//! payoff.
//!
//! # Mechanism
//!
//! 32 random bytes generated by the platform RNG at vault
//! initialisation, sealed into the vault file with the unlock
//! credential's KEK, and unsealed into memory only for the duration
//! of a session.
//!
//! In memory, the secret lives inside a `Zeroizing<[u8; 32]>`.  On
//! drop, the bytes are explicitly overwritten with zeros via the
//! `zeroize` crate.  This closes:
//!
//! - **Core-dump leaks** — paired with `prctl(PR_SET_DUMPABLE, 0)`
//!   in the launcher.
//! - **Heap-reuse leaks** — the allocator may hand out the bytes to
//!   a subsequent allocation; zeroization makes that allocation see
//!   zeros instead of secret bytes.
//! - **Paged-out swap leaks** — paired with `mlockall` in the
//!   launcher, the bytes never reach the page file.
//!
//! # Threat model boundaries
//!
//! - Defeats: passive reads of process memory after secret usage.
//! - Does NOT defeat: live reads of process memory DURING usage
//!   (require seccomp + Landlock + ptrace_scope=2 to block).
//! - Does NOT defeat: kernel-privilege attackers who read the
//!   process address space directly (v3 confidential-VM mitigates).

use rand::RngCore;
use zeroize::Zeroizing;

use crate::errors::Result;

/// Fixed length of the per-host secret in bytes.  32 bytes = the
/// SHA-256 output size, which is the natural input width for HKDF's
/// extract phase.
pub const PER_HOST_SECRET_LEN: usize = 32;

/// Per-host secret.
///
/// Construct via [`PerHostSecret::generate`] (creates a fresh
/// random secret from the platform RNG) or
/// [`PerHostSecret::from_bytes`] (loads bytes from the unsealed
/// vault payload).
///
/// The byte slice is exposed only via [`PerHostSecret::expose`]
/// which returns a borrowed `&[u8]`.  No `Clone`, no `Copy`, no
/// public `Debug` printing — the value lives in exactly one
/// location and is dropped (and zeroized) at exactly one site.
pub struct PerHostSecret(Zeroizing<[u8; PER_HOST_SECRET_LEN]>);

impl PerHostSecret {
    /// Generate a fresh random per-host secret using the platform RNG.
    ///
    /// Use this exactly once per host — at vault initialisation.
    /// Subsequent sessions load the secret from the unsealed vault
    /// via [`PerHostSecret::from_bytes`].
    #[must_use]
    pub fn generate() -> Self {
        let mut buf = Zeroizing::new([0u8; PER_HOST_SECRET_LEN]);
        rand::thread_rng().fill_bytes(buf.as_mut_slice());
        Self(buf)
    }

    /// Construct a `PerHostSecret` from previously-generated bytes.
    ///
    /// Returns `Error::OutOfRange` if `bytes.len() != PER_HOST_SECRET_LEN`.
    ///
    /// # Errors
    ///
    /// `Error::OutOfRange` when the input is not exactly the
    /// required length.
    pub fn from_bytes(bytes: &[u8]) -> Result<Self> {
        if bytes.len() != PER_HOST_SECRET_LEN {
            return Err(crate::errors::Error::OutOfRange {
                index: bytes.len(),
                size: PER_HOST_SECRET_LEN,
            });
        }
        let mut buf = Zeroizing::new([0u8; PER_HOST_SECRET_LEN]);
        buf.copy_from_slice(bytes);
        Ok(Self(buf))
    }

    /// Expose the secret bytes as a borrowed slice for use by the
    /// `key_derivation` module.
    ///
    /// **Discipline:** consumers should hand the slice directly to
    /// HKDF and not retain a copy.  Holding a long-lived reference
    /// to this slice keeps the secret pages live and defeats the
    /// zeroize-on-drop guarantee.
    #[must_use]
    pub fn expose(&self) -> &[u8] {
        self.0.as_slice()
    }
}

// Deliberately omitted: Clone, Copy, Debug.  Cloning the secret
// proliferates plaintext copies; Debug printing exposes the bytes to
// any sink that captures `{:?}` output.  Operators who need a fresh
// secret should generate one; operators who need to inspect the
// secret have to dump memory deliberately.

#[cfg(test)]
mod tests {
    use super::{PerHostSecret, PER_HOST_SECRET_LEN};
    use crate::errors::Error;

    #[test]
    fn generate_produces_fixed_length() {
        let secret = PerHostSecret::generate();
        assert_eq!(secret.expose().len(), PER_HOST_SECRET_LEN);
    }

    #[test]
    fn generate_produces_distinct_secrets() {
        let a = PerHostSecret::generate();
        let b = PerHostSecret::generate();
        // Probability of collision: 2^-256.  Test should never flake.
        assert_ne!(a.expose(), b.expose());
    }

    #[test]
    fn from_bytes_accepts_correct_length() {
        let bytes = [42u8; PER_HOST_SECRET_LEN];
        let Ok(secret) = PerHostSecret::from_bytes(&bytes) else {
            panic!("32-byte input should be accepted");
        };
        assert_eq!(secret.expose(), &bytes);
    }

    #[test]
    fn from_bytes_rejects_too_short() {
        let bytes = [1u8; 16];
        // Deliberately use `match` instead of `unwrap_err` — the Ok
        // variant doesn't impl Debug (PerHostSecret has no Debug).
        match PerHostSecret::from_bytes(&bytes) {
            Err(Error::OutOfRange { index: 16, size: 32 }) => {}
            Err(other) => panic!("unexpected error: {other}"),
            Ok(_) => panic!("16-byte input should be rejected"),
        }
    }

    #[test]
    fn from_bytes_rejects_too_long() {
        let bytes = [1u8; 33];
        match PerHostSecret::from_bytes(&bytes) {
            Err(Error::OutOfRange { index: 33, size: 32 }) => {}
            Err(other) => panic!("unexpected error: {other}"),
            Ok(_) => panic!("33-byte input should be rejected"),
        }
    }
}
